services:
  ntp:
    container_name: ntp
    image: cturra/ntp:latest
    restart: unless-stopped
    networks:
      - homelab-network
    ports:
      - 123:123/udp
    environment:
      - NTP_SERVERS=time.cloudflare.com,time1.google.com,time2.google.com,time3.google.com
      - LOG_LEVEL=0
      - TZ=Africa/Nairobi
      - NOCLIENTLOG=true
      # - ENABLE_NTS=true # Google NTS doesn't like this
    security_opt:
      - no-new-privileges:true
