services:
  littlelink:
    container_name: littlelink
    image: ghcr.io/techno-tim/littlelink-server:latest
    restart: unless-stopped
    networks:
      - homelab-network
    environment:
      - META_TITLE=Rodney Osodo LittleLink
      - META_DESCRIPTION=Software Engineer | Content Creator | Homelab | 🇰🇪
      - META_AUTHOR=Rodney Osodo
      - META_KEYWORDS=HomeLab, Software Engineering, Mechatronics Engineering
      - LANG=en
      - META_INDEX_STATUS=all
      - OG_SITE_NAME=Rodney Osodo
      - OG_TITLE=Rodney Osodo
      - OG_DESCRIPTION=The home of Rodney Osodo
      - OG_URL=https://rodneyosodo.com
      - OG_IMAGE=https://pbs.twimg.com/profile_images/1266015480206237704/j78P7w8U_400x400.jpg
      - OG_IMAGE_WIDTH=400
      - OG_IMAGE_HEIGHT=400
      - THEME=Dark
      - FAVICON_URL=https://pbs.twimg.com/profile_images/1266015480206237704/j78P7w8U_400x400.jpg
      - AVATAR_URL=https://pbs.twimg.com/profile_images/1266015480206237704/j78P7w8U_400x400.jpg
      - AVATAR_2X_URL=https://pbs.twimg.com/profile_images/1266015480206237704/j78P7w8U_400x400.jpg
      - AVATAR_ALT=Rodney Osodo Profile Pic
      - NAME=RodneyOsodo
      - BIO=Software Engineer | Content Creator | Homelab | 🇰🇪
      - BUTTON_ORDER=GITHUB,TIKTOK,TWITTER,LINKED_IN,YOUTUBE,INSTAGRAM
      - GITHUB=https://github.com/rodneyosodo
      - TIKTOK=https://www.tiktok.com/@b1ackd0t
      - TWITTER=https://twitter.com/b1ackd0t
      - LINKED_IN=https://www.linkedin.com/in/rodneyosodo/
      - YOUTUBE=https://www.youtube.com/@rodneyosodo
      - INSTAGRAM=https://www.instagram.com/rodneyosodo/
      - FOOTER=Rodney Osodo © 2022
    ports:
      - 2040:3000
    security_opt:
      - no-new-privileges:true
