services:
  jupyter:
    container_name: jupyter
    image: quay.io/jupyter/minimal-notebook:latest
    restart: unless-stopped
    networks:
      - homelab-network
    security_opt:
      - no-new-privileges:true
    ports:
      - 4000:8888
    volumes:
      - ~/docker-volumes/jupyter:/home/rodneyosodo/work
    command: start-notebook.py --IdentityProvider.token='' --PasswordIdentityProvider.hashed_password="'${JUPYTER_PASSWORD}'"
    environment:
      - NB_UID=1000
      - NB_GID=1000
      - NB_USER=rodneyosodo
      - HOME=/home/rodneyosodo
      - CHOWN_HOME=yes
      - PASSWORD=${JUPYTER_PASSWORD}
    working_dir: /home/rodneyosodo
    user: root
