services:
  wireguard:
    container_name: wireguard
    image: ghcr.io/wg-easy/wg-easy:latest
    restart: unless-stopped
    networks:
      - homelab-network
    environment:
      - LANG=en
      - WG_HOST=vpn.homelab.rodneyosodo.com
      - PASSWORD=${WIREGUARD_PASSWORD}
    volumes:
      - ~/docker-volumes/wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    security_opt:
      - no-new-privileges:true
