services:
  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:v1.94.1
    restart: unless-stopped
    networks:
      - homelab-network
    security_opt:
      - no-new-privileges:true
    command: ["start.sh", "immich"]
    volumes:
      - ~/docker-volumes/immich-images:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 2090:3001
    depends_on:
      - redis
      - immich-postgres
    environment:
      - TZ=Africa/Nairobi
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - DB_HOSTNAME=immich-postgres
      - DB_PORT=5432
      - DB_USERNAME=${IMMICH_POSTGRES_USER}
      - DB_PASSWORD=${IMMICH_POSTGRES_PASSWORD}
      - DB_DATABASE_NAME=${IMMICH_POSTGRES_DB}
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  immich-microservices:
    container_name: immich-microservices
    image: ghcr.io/immich-app/immich-server:v1.94.1
    restart: unless-stopped
    networks:
      - homelab-network
    security_opt:
      - no-new-privileges:true
    devices:
      - /dev/dri:/dev/dri # If using Intel QuickSync or VAAPI
    command: ["start.sh", "microservices"]
    volumes:
      - ~/docker-volumes/immich-images:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - redis
      - immich-postgres
    environment:
      - TZ=Africa/Nairobi
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - DB_HOSTNAME=immich-postgres
      - DB_PORT=5432
      - DB_USERNAME=${IMMICH_POSTGRES_USER}
      - DB_PASSWORD=${IMMICH_POSTGRES_PASSWORD}
      - DB_DATABASE_NAME=${IMMICH_POSTGRES_DB}

  immich-machine-learning:
    container_name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:v1.94.1
    restart: unless-stopped
    networks:
      - homelab-network
    security_opt:
      - no-new-privileges:true
    volumes:
      - ~/docker-volumes/immich-cache:/cache

  immich-postgres:
    container_name: immich-postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11
    restart: unless-stopped
    networks:
      - homelab-network
    security_opt:
      - no-new-privileges:true
    environment:
      POSTGRES_PASSWORD: ${IMMICH_POSTGRES_PASSWORD}
      POSTGRES_USER: ${IMMICH_POSTGRES_USER}
      POSTGRES_DB: ${IMMICH_POSTGRES_DB}
    volumes:
      - ~/docker-volumes/immich-postgres-data:/var/lib/postgresql/data
